//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendar
    {
        public string corp_id { get; set; }
        public string calendar_id { get; set; }
        public string week_start { get; set; }
        public string week_end { get; set; }
        public decimal mhn0 { get; set; }
        public decimal mhn1 { get; set; }
        public decimal mhn2 { get; set; }
        public decimal mhn3 { get; set; }
        public decimal mhn4 { get; set; }
        public decimal mhn5 { get; set; }
        public decimal mhn6 { get; set; }
        public string date0 { get; set; }
        public string date1 { get; set; }
        public string date2 { get; set; }
        public string date3 { get; set; }
        public string date4 { get; set; }
        public string date5 { get; set; }
        public string date6 { get; set; }
        public string WKflag0 { get; set; }
        public string WKflag1 { get; set; }
        public string WKflag2 { get; set; }
        public string WKflag3 { get; set; }
        public string WKflag4 { get; set; }
        public string WKflag5 { get; set; }
        public string WKflag6 { get; set; }
    }
}
