//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_leave_storage_year_summary_013
    {
        public string data_year { get; set; }
        public string employee_id { get; set; }
        public string keep_year { get; set; }
        public decimal leave_keep { get; set; }
        public Nullable<System.DateTime> schedule_date { get; set; }
        public string old_employee_id { get; set; }
        public string corp_id { get; set; }
    }
}
