//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_data_tmp_leave
    {
        public string mh_id { get; set; }
        public string mh_yyyymm { get; set; }
        public string cost_center { get; set; }
        public string mh_group { get; set; }
        public string employee_id { get; set; }
        public string cost_code { get; set; }
        public string equip_no { get; set; }
        public decimal mhn0 { get; set; }
        public decimal mhn1 { get; set; }
        public decimal mhn2 { get; set; }
        public decimal mhn3 { get; set; }
        public decimal mhn4 { get; set; }
        public decimal mhn5 { get; set; }
        public decimal mhn6 { get; set; }
        public decimal mhn_tot { get; set; }
        public string week_end { get; set; }
        public string calendar_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string keyin_by { get; set; }
        public string keyin_by_corp { get; set; }
        public string check_by { get; set; }
        public string check_by_corp { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string approve_by { get; set; }
        public string approve_by_corp { get; set; }
        public Nullable<System.DateTime> approve_date { get; set; }
        public string form_id { get; set; }
        public string corp_id { get; set; }
        public string checker { get; set; }
        public string checker_corp { get; set; }
        public string approver { get; set; }
        public string approver_corp { get; set; }
    }
}
