//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_for_salary
    {
        public string corp_id { get; set; }
        public string mh_type { get; set; }
        public string mh_id { get; set; }
        public string data_yyyymm { get; set; }
        public string resign_status { get; set; }
        public string employee_id { get; set; }
        public string week_end { get; set; }
        public string mh_date { get; set; }
        public string leave_code { get; set; }
        public Nullable<decimal> mhn_tot { get; set; }
        public string sex { get; set; }
        public string prj_no { get; set; }
        public string unit_area { get; set; }
        public Nullable<decimal> ot_100 { get; set; }
        public Nullable<decimal> ot_133 { get; set; }
        public Nullable<decimal> ot_166 { get; set; }
        public Nullable<decimal> ot_200 { get; set; }
        public Nullable<decimal> tax_100 { get; set; }
        public Nullable<decimal> tax_133 { get; set; }
        public Nullable<decimal> tax_166 { get; set; }
        public Nullable<decimal> tax_200 { get; set; }
        public Nullable<decimal> d_tax_100 { get; set; }
        public Nullable<decimal> d_tax_133 { get; set; }
        public Nullable<decimal> d_tax_166 { get; set; }
        public Nullable<decimal> d_tax_200 { get; set; }
        public Nullable<decimal> m_tax_100 { get; set; }
        public Nullable<decimal> m_tax_133 { get; set; }
        public Nullable<decimal> m_tax_166 { get; set; }
        public Nullable<decimal> m_tax_200 { get; set; }
        public Nullable<decimal> g_ot_permit { get; set; }
        public Nullable<decimal> g_ot_100 { get; set; }
        public Nullable<decimal> g_ot_133 { get; set; }
        public Nullable<decimal> g_ot_166 { get; set; }
        public Nullable<decimal> g_ot_200 { get; set; }
        public Nullable<decimal> g_tax_100 { get; set; }
        public Nullable<decimal> g_tax_133 { get; set; }
        public Nullable<decimal> g_tax_166 { get; set; }
        public Nullable<decimal> g_tax_200 { get; set; }
        public string tax_sw { get; set; }
        public string calendar_id { get; set; }
        public Nullable<decimal> regular_mh { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
