//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_z_code_list
    {
        public string corp_id { get; set; }
        public string code_type { get; set; }
        public string code_id { get; set; }
        public string code_desc { get; set; }
        public System.DateTime modify_date { get; set; }
        public string modify_by { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    }
}
