//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_pm_in_site
    {
        public string corp_id { get; set; }
        public string prj_key { get; set; }
        public string employee_id { get; set; }
        public string remark { get; set; }
    }
}
