//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_overtime_form_detail
    {
        public string detail_id { get; set; }
        public string form_id { get; set; }
        public string mh_group { get; set; }
        public string cost_center { get; set; }
        public string employee_id { get; set; }
        public string prj_no { get; set; }
        public string cost_code { get; set; }
        public string phase { get; set; }
        public string discipline { get; set; }
        public string calendar_id { get; set; }
        public decimal normal_hr { get; set; }
        public string overtime_date { get; set; }
        public decimal overtime_hr { get; set; }
        public string overtime_time { get; set; }
        public string overtime_week { get; set; }
        public string overtime_option { get; set; }
        public string week_end { get; set; }
        public string checker { get; set; }
        public string checker_corp { get; set; }
        public string check_by { get; set; }
        public string check_by_corp { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string approver { get; set; }
        public string approver_corp { get; set; }
        public string approve_by { get; set; }
        public string approve_by_corp { get; set; }
        public Nullable<System.DateTime> approve_date { get; set; }
        public string reject { get; set; }
        public string status { get; set; }
        public string keyin_by { get; set; }
        public string keyin_by_corp { get; set; }
        public System.DateTime keyin_date { get; set; }
        public Nullable<System.DateTime> mod_date { get; set; }
        public string corp_id { get; set; }
    }
}
