//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_data1
    {
        public string mh_id { get; set; }
        public string mh_yyyymm { get; set; }
        public string cost_center { get; set; }
        public string mh_group { get; set; }
        public string employee_id { get; set; }
        public string prj_no { get; set; }
        public string cost_code { get; set; }
        public string class_id { get; set; }
        public string unit_area { get; set; }
        public string sys_no { get; set; }
        public string equip_no { get; set; }
        public string serial_no { get; set; }
        public string recycle_wk { get; set; }
        public decimal mhn_tot { get; set; }
        public decimal mho_tot { get; set; }
        public string week_end { get; set; }
        public string calendar_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string keyin_by { get; set; }
        public string keyin_by_corp { get; set; }
        public string sign_sw { get; set; }
        public string cost_date { get; set; }
        public string salary_date { get; set; }
        public Nullable<System.DateTime> mod_date { get; set; }
        public string mod_by { get; set; }
        public string mod_by_corp { get; set; }
        public string cost_yyyymm { get; set; }
        public string phase { get; set; }
        public string discipline { get; set; }
        public string corp_id { get; set; }
    }
}
