//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_corp_tab
    {
        public string corp_id { get; set; }
        public string mh_enabled_flag { get; set; }
        public string mh_enabled_yyyymm { get; set; }
        public string mh_sign_level { get; set; }
        public int mh_Decimal_point { get; set; }
        public string leave_enabled_flag { get; set; }
        public string leave_enabled_yyyymm { get; set; }
        public string leave_sign_level { get; set; }
        public int Leave_Decimal_point { get; set; }
        public string OT_enabled_flag { get; set; }
        public string OT_enabled_yyyymm { get; set; }
        public string OT_sign_level { get; set; }
        public int OT_Decimal_point { get; set; }
        public string OT_Option_flag { get; set; }
    }
}
