//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_holiday
    {
        public string data_id { get; set; }
        public string corp_id { get; set; }
        public string calendar_id { get; set; }
        public string mh_date { get; set; }
        public string holiday_desc { get; set; }
        public decimal rate { get; set; }
        public string keyin_by { get; set; }
        public Nullable<System.DateTime> keyin_date { get; set; }
    }
}
