//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_auto_gen_mh_special
    {
        public string corp_id { get; set; }
        public string employee_id { get; set; }
        public string need_keyin { get; set; }
        public System.DateTime create_date { get; set; }
        public string remark { get; set; }
    }
}
