//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_leave_form_detail
    {
        public string detail_id { get; set; }
        public string form_id { get; set; }
        public string number { get; set; }
        public string employee_id { get; set; }
        public string mh_group { get; set; }
        public string cost_center { get; set; }
        public string calendar_id { get; set; }
        public decimal normal_hr { get; set; }
        public string leave_date { get; set; }
        public string leave_wk { get; set; }
        public decimal leave_hr { get; set; }
        public string leave_time { get; set; }
        public string corp_id { get; set; }
    }
}
