//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_apply_leave
    {
        public string data_id { get; set; }
        public string corp_id { get; set; }
        public string employee_id { get; set; }
        public string leave_code { get; set; }
        public string beg_date { get; set; }
        public string end_date { get; set; }
        public string apply_year { get; set; }
        public decimal apply_mh { get; set; }
        public string keyin_by { get; set; }
        public Nullable<System.DateTime> keyin_date { get; set; }
        public string reason { get; set; }
        public string confirm_flag { get; set; }
        public string confirm_by { get; set; }
        public Nullable<System.DateTime> confirm_date { get; set; }
    }
}
