//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int rowid { get; set; }
        public string ntaccount { get; set; }
        public string messagedesc { get; set; }
        public string url { get; set; }
        public int priorityid { get; set; }
        public System.DateTime indate { get; set; }
        public System.DateTime duedate { get; set; }
        public int cateid { get; set; }
        public string subcate { get; set; }
        public int recid { get; set; }
        public string oriaccount { get; set; }
        public string oriname { get; set; }
        public string prj_no { get; set; }
        public string subcate_desc { get; set; }
        public string parameter { get; set; }
        public string internet_flag { get; set; }
        public string corp_id { get; set; }
    }
}
