//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oversea_leave_confirm
    {
        public string data_id { get; set; }
        public string seq_no { get; set; }
        public string employee_id { get; set; }
        public string year { get; set; }
        public decimal permit { get; set; }
        public decimal used { get; set; }
        public decimal leave_left { get; set; }
        public System.DateTime create_date { get; set; }
        public string sal_yyyymm { get; set; }
        public string corp_id { get; set; }
        public string note { get; set; }
    }
}
