//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class corp_leave_permit
    {
        public string corp_id { get; set; }
        public string employee_id { get; set; }
        public decimal vacation_permit_nxt { get; set; }
        public decimal vacation_permit_cur { get; set; }
        public decimal vacation_permit_lst { get; set; }
        public decimal vacation_permit_b_lst { get; set; }
        public string mod_by { get; set; }
        public System.DateTime mod_date { get; set; }
        public string auto_flag { get; set; }
    }
}
