//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_overtime_form
    {
        public string form_id { get; set; }
        public string employee_id { get; set; }
        public string prj_no { get; set; }
        public string cost_code { get; set; }
        public string phase { get; set; }
        public string discipline { get; set; }
        public string beg_date { get; set; }
        public string end_date { get; set; }
        public string reason { get; set; }
        public string keyin_by { get; set; }
        public string keyin_by_corp { get; set; }
        public Nullable<System.DateTime> keyin_date { get; set; }
        public string corp_id { get; set; }
    }
}
