//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_deputy_item_list
    {
        public string functionID { get; set; }
        public string function_Desc { get; set; }
        public string detail_flag { get; set; }
        public string URL { get; set; }
        public int FUNCID { get; set; }
        public string Sort_Key { get; set; }
    }
}
