//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_checker_log
    {
        public string mh_group { get; set; }
        public string employee_id { get; set; }
        public string checker_id { get; set; }
        public string keyin_by { get; set; }
        public Nullable<System.DateTime> keyin_date { get; set; }
        public string work_site { get; set; }
        public string corp_id { get; set; }
        public System.DateTime delete_date { get; set; }
    }
}
