//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_leave_used_record_013_9933002
    {
        public string corp_id { get; set; }
        public string record_id { get; set; }
        public string detail_id { get; set; }
        public string form_id { get; set; }
        public string number { get; set; }
        public string employee_id { get; set; }
        public string mh_yyyymm { get; set; }
        public decimal leave_hr { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
