//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_leave_form
    {
        public string form_id { get; set; }
        public string number { get; set; }
        public string employee_id { get; set; }
        public string leave_code { get; set; }
        public string beg_date { get; set; }
        public string end_date { get; set; }
        public decimal total_hr { get; set; }
        public string reason { get; set; }
        public string prj_no { get; set; }
        public string deputy { get; set; }
        public string deputy_corp { get; set; }
        public string deputy_flag { get; set; }
        public string deputy_reject { get; set; }
        public Nullable<System.DateTime> deputy_date { get; set; }
        public string checker { get; set; }
        public string checker_corp { get; set; }
        public string check_by { get; set; }
        public string check_by_corp { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string approver { get; set; }
        public string approver_corp { get; set; }
        public string approve_by { get; set; }
        public string approve_by_corp { get; set; }
        public Nullable<System.DateTime> approve_date { get; set; }
        public string reject { get; set; }
        public string status { get; set; }
        public string keyin_by { get; set; }
        public string keyin_by_corp { get; set; }
        public Nullable<System.DateTime> keyin_date { get; set; }
        public Nullable<System.DateTime> mod_date { get; set; }
        public string file_url { get; set; }
        public string is_vip { get; set; }
        public string revoke_desc { get; set; }
        public Nullable<System.DateTime> revoke_date { get; set; }
        public string corp_id { get; set; }
    }
}
