//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_ot_over_46_permit
    {
        public string data_id { get; set; }
        public string corp_id { get; set; }
        public string employee_id { get; set; }
        public string beg_yyyymm { get; set; }
        public string end_yyyymm { get; set; }
        public decimal limit_ot { get; set; }
        public string keyin_by { get; set; }
        public System.DateTime keyin_date { get; set; }
    }
}
