//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_for_salary_oversea
    {
        public string mh_type { get; set; }
        public string mh_id { get; set; }
        public string data_yyyymm { get; set; }
        public string resign_status { get; set; }
        public string employee_id { get; set; }
        public string week_end { get; set; }
        public string mh_date { get; set; }
        public string leave_code { get; set; }
        public Nullable<decimal> mh_leave { get; set; }
        public string sex { get; set; }
        public string prj_no { get; set; }
        public string unit_area { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string corp_id { get; set; }
    }
}
