//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_deputy_detail
    {
        public string detail_id { get; set; }
        public string data_id { get; set; }
        public string employee_id { get; set; }
        public string prj_no { get; set; }
    }
}
