//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_message_for_003_left
    {
        public string mm { get; set; }
        public string mh_group { get; set; }
        public string employee_id { get; set; }
        public string name_c { get; set; }
        public System.DateTime enter_date { get; set; }
        public decimal leave_permit { get; set; }
        public decimal leave_used { get; set; }
        public System.DateTime exec_date { get; set; }
        public string corp_id { get; set; }
    }
}
