//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_leave_hr_list
    {
        public Nullable<System.DateTime> Fix_HR { get; set; }
        public Nullable<System.DateTime> Nor_HR { get; set; }
        public Nullable<decimal> Base { get; set; }
        public Nullable<int> Mod_Base { get; set; }
        public Nullable<System.DateTime> Break_Init { get; set; }
        public Nullable<System.DateTime> Break_End { get; set; }
        public string corp_id { get; set; }
    }
}
