//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_zz_code_type
    {
        public string code_type { get; set; }
        public string type_desc { get; set; }
        public string remark { get; set; }
        public bool corp_visible { get; set; }
        public bool user_maintainable { get; set; }
        public bool in_code_list { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string modify_by { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string module_id { get; set; }
    }
}
