//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_data_pre
    {
        public string mh_id { get; set; }
        public string mh_yyyymm { get; set; }
        public string cost_center { get; set; }
        public string mh_group { get; set; }
        public string employee_id { get; set; }
        public string prj_no { get; set; }
        public string cost_code { get; set; }
        public string class_id { get; set; }
        public string unit_area { get; set; }
        public string sys_no { get; set; }
        public string equip_no { get; set; }
        public string serial_no { get; set; }
        public string recycle_wk { get; set; }
        public decimal mhn0 { get; set; }
        public decimal mho0 { get; set; }
        public decimal mhn1 { get; set; }
        public decimal mho1 { get; set; }
        public decimal mhn2 { get; set; }
        public decimal mho2 { get; set; }
        public decimal mhn3 { get; set; }
        public decimal mho3 { get; set; }
        public decimal mhn4 { get; set; }
        public decimal mho4 { get; set; }
        public decimal mhn5 { get; set; }
        public decimal mho5 { get; set; }
        public decimal mhn6 { get; set; }
        public decimal mho6 { get; set; }
        public decimal mhn_tot { get; set; }
        public decimal mho_tot { get; set; }
        public string week_end { get; set; }
        public string calendar_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string keyin_by { get; set; }
        public string keyin_by_corp { get; set; }
        public string sign_sw { get; set; }
        public string check_by { get; set; }
        public string check_by_corp { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string approve_by { get; set; }
        public string approve_by_corp { get; set; }
        public Nullable<System.DateTime> approve_date { get; set; }
        public string cost_date { get; set; }
        public string salary_date { get; set; }
        public Nullable<System.DateTime> mod_date { get; set; }
        public string mod_by { get; set; }
        public string mod_by_corp { get; set; }
        public string form_id { get; set; }
        public string phase { get; set; }
        public string discipline { get; set; }
        public string org_phase { get; set; }
        public string corp_id { get; set; }
        public string checker { get; set; }
        public string checker_corp { get; set; }
        public string approver { get; set; }
        public string approver_corp { get; set; }
        public string employee_status0 { get; set; }
        public string employee_status1 { get; set; }
        public string employee_status2 { get; set; }
        public string employee_status3 { get; set; }
        public string employee_status4 { get; set; }
        public string employee_status5 { get; set; }
        public string employee_status6 { get; set; }
        public string remark { get; set; }
    }
}
