//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_leave_storage_053
    {
        public string corp_id { get; set; }
        public string mh_yyyymm { get; set; }
        public string employee_id { get; set; }
        public decimal leave_storage { get; set; }
        public decimal leave_used { get; set; }
        public decimal leave_left { get; set; }
        public Nullable<System.DateTime> schedule_date { get; set; }
    }
}
