//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmh_for_mp
    {
        public string mh_yyyymm { get; set; }
        public string emp_type { get; set; }
        public string cost_center { get; set; }
        public decimal r1 { get; set; }
        public decimal o1 { get; set; }
        public decimal r2 { get; set; }
        public decimal o2 { get; set; }
        public decimal r3 { get; set; }
        public decimal o3 { get; set; }
        public decimal r4 { get; set; }
        public decimal o4 { get; set; }
        public decimal r5 { get; set; }
        public decimal o5 { get; set; }
        public decimal r6 { get; set; }
        public decimal o6 { get; set; }
        public decimal r7 { get; set; }
        public decimal o7 { get; set; }
        public decimal r8 { get; set; }
        public decimal o8 { get; set; }
        public decimal r9 { get; set; }
        public decimal o9 { get; set; }
        public decimal leave_tot { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string corp_id { get; set; }
    }
}
