//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_emp_OT_flag
    {
        public string corp_id { get; set; }
        public string employee_id { get; set; }
        public string OT_flag { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
