//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class month_frozen
    {
        public string mh_yyyymm { get; set; }
        public Nullable<System.DateTime> cost_date { get; set; }
        public Nullable<System.DateTime> frozen_date { get; set; }
        public string corp_id { get; set; }
    }
}
