//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCallSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oversea_leave_to_bonus_record
    {
        public string data_id { get; set; }
        public string seq_no { get; set; }
        public string employee_id { get; set; }
        public string calendar_id { get; set; }
        public string trans_date { get; set; }
        public string oversea_date { get; set; }
        public string return_date { get; set; }
        public string trans_edit_date { get; set; }
        public string oversea_edit_date { get; set; }
        public string return_edit_date { get; set; }
        public string salary_flag { get; set; }
        public System.DateTime create_date { get; set; }
        public string modify_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string corp_id { get; set; }
    }
}
